name: BE Dev PR pipeline.

on:
  pull_request:
    branches: ["development"]

jobs:
  build:
    name: Dev PR pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'back_end'  # Update this if your project files are in a specific directory
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set Up Gradle
        run: |
          chmod +x gradlew
          ./gradlew wrapper
      - name: Build Project
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Check formatting
        run: |
          chmod +x gradlew
          ./gradlew check
      - name: Run Tests
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Generate Coverage Report
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport
      - name: Check Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestCoverageVerification